package com.kurento.commons.ua.event;

import java.util.EventObject;

import com.kurento.commons.ua.Call;

/**
 * CallEvent is generated by the Call when there is a relevant transition
 * to be notified
 * 
 * @author Kurento
 * 
 */
public class CallEvent extends EventObject {

	private static final long serialVersionUID = -6895550063104778497L;

	/**
	 * Call negotiation has completed successfully and media channels are setup
	 */
	public static final CallEventEnum CALL_SETUP = CallEventEnum.CALL_SETUP;
	/**
	 * Call rejected by the called party
	 */
	public static final CallEventEnum CALL_REJECT = CallEventEnum.CALL_REJECT;
	/**
	 * Call canceled by the calling party
	 */
	public static final CallEventEnum CALL_CANCEL = CallEventEnum.CALL_CANCEL;
	/**
	 * Call terminated (hang up) by one of the parties
	 */
	public static final CallEventEnum CALL_TERMINATE = CallEventEnum.CALL_TERMINATE;
	/**
	 * Call setup failure due to a protocol problem
	 */
	public static final CallEventEnum CALL_ERROR = CallEventEnum.CALL_ERROR;
	/**
	 * Call setup failure due to incompatible media formats
	 */
	public static final CallEventEnum MEDIA_NOT_SUPPORTED = CallEventEnum.MEDIA_NOT_SUPPORTED;
	/**
	 * Call setup failure due to lack of media resources. No ports available
	 */
	public static final CallEventEnum MEDIA_RESOURCE_NOT_AVAILABLE = CallEventEnum.MEDIA_RESOURCE_NOT_AVAILABLE;
	/**
	 * Internal error within the local party prevents a normal negotiation flow
	 */
	public static final CallEventEnum SERVER_INTERNAL_ERROR = CallEventEnum.SERVER_INTERNAL_ERROR;
	
	private CallEventEnum eventType;

	public CallEvent(CallEventEnum eventType, Call source) {
		super(source);
		this.eventType = eventType;
	}

	/**
	 * Set event source. The Call originating the event
	 * @param source
	 */
	public void setSource(Call source) {
		this.source = source;
	}

	/**
	 * Get Call that sourced the event
	 */
	public Call getSource() {
		return (Call) source;
	}

	/**
	 * Set the event that has to be notified
	 * @param eventType
	 */
	public void setEventType(CallEventEnum eventType) {
		this.eventType = eventType;
	}

	/**
	 * Returns the event type
	 * @return Event type
	 */
	public CallEventEnum getEventType() {
		return eventType;
	}

	public String toString() {
		return eventType.toString();
	}

}
