package com.kurento.commons.ua.event;

import java.util.EventObject;

import com.kurento.commons.ua.Call;
import com.kurento.commons.ua.Conference;
import com.kurento.commons.ua.EndPoint;

/**
 * EndPointsEvents are generated by a EndPoint when a state transition
 * takes place within the service element
 * 
 * @author Kurento
 * 
 */
public class EndPointEvent extends EventObject {

	private static final long serialVersionUID = 6307930313482035976L;
	
	/**
	 * This event signals the UA received a call INVITE for the EndPoint URI
	 */
	public static final EndpointEventEnum INCOMING_CALL = EndpointEventEnum.INCOMING_CALL;
	/**
	 * This event signals the UA successfully registered the URI
	 */
	public static final EndpointEventEnum REGISTER_USER_SUCESSFUL = EndpointEventEnum.REGISTER_USER_SUCESSFUL;
	/**
	 * This event signals the UA successfully unregistered the URI
	 */
	public static final EndpointEventEnum UNREGISTER_USER_SUCESSFUL = EndpointEventEnum.UNREGISTER_USER_SUCESSFUL;
	/**
	 * This event signals the REGISTER rejected to register the URI with a 403
	 * code
	 */
	public static final EndpointEventEnum REGISTER_USER_NOT_FOUND = EndpointEventEnum.REGISTER_USER_NOT_FOUND;
	/**
	 * This event signals the REGISTER rejected to unregister the URI with a 403
	 * code
	 */
	public static final EndpointEventEnum UNREGISTER_USER_NOT_FOUND = EndpointEventEnum.UNREGISTER_USER_NOT_FOUND;
	/**
	 * This event signals a register failure with 4xx response
	 */
	public static final EndpointEventEnum REGISTER_USER_FAIL = EndpointEventEnum.REGISTER_USER_FAIL;
	/**
	 * This event signals a unregister failure with 4xx response
	 */
	public static final EndpointEventEnum UNREGISTER_USER_FAIL = EndpointEventEnum.UNREGISTER_USER_FAIL;
	/**
	 * This event signals an internal UA error preventing the REGISTER operation
	 * to complete sucessfully
	 */
	public static final EndpointEventEnum MEDIA_NOT_SUPPORTED = EndpointEventEnum.MEDIA_NOT_SUPPORTED;
	/**
	 * Call setup failure due to lack of media resources. No ports available
	 */
	public static final EndpointEventEnum MEDIA_RESOURCE_NOT_AVAILABLE = EndpointEventEnum.MEDIA_RESOURCE_NOT_AVAILABLE;
	/**
	 * Internal error within the local party prevents a normal negotiation flow
	 */
	public static final EndpointEventEnum SERVER_INTERNAL_ERROR = EndpointEventEnum.SERVER_INTERNAL_ERROR;
	/**
	 * This event signals a problem with authorization
	 */
	public static final EndpointEventEnum AUTHORIZATION_FAILURE = EndpointEventEnum.AUTHORIZATION_FAILURE;

	private final EndpointEventEnum eventType;

	/**
	 * This constructor allows to create an event whose source is a call managed
	 * by the EndPoint
	 * 
	 * @param eventType
	 * @param source
	 *            Call generating this event
	 */
	public EndPointEvent(EndpointEventEnum eventType, Call source) {
		super(source);
		this.eventType = eventType;
	}

	/**
	 * This constructor allows to create an event whose source is a conference
	 * managed by the EndPoint
	 * 
	 * @param eventType
	 * @param source
	 *            Call generating this event
	 */
	public EndPointEvent(EndpointEventEnum eventType, Conference source) {
		super(source);
		this.eventType = eventType;
	}

	/**
	 * This constructor allows to create an event whose source is the EndPoint
	 * itself
	 * 
	 * @param eventType
	 * @param source
	 */
	public EndPointEvent(EndpointEventEnum eventType, EndPoint source) {
		super(source);
		this.eventType = eventType;
	}

	/**
	 * Get EndPoint source. This function can be called with events:
	 * <ul>
	 * <li>INCOMING_CALL
	 * </ul>
	 * When source is not a Call this method returns null
	 * 
	 * @return Call generating the event
	 */

	public Call getCallSource() {
		if (source instanceof Call)
			return (Call) source;
		else
			return null;
	}

	/**
	 * Get Conference source. This function can be called with events:
	 * <ul>
	 * <li>INCOMING_CALL
	 * </ul>
	 * When source is not a Call this method returns null
	 * 
	 * @return Call generating the event
	 */

	public Conference getConferenceSource() {
		if (source instanceof Conference)
			return (Conference) source;
		else
			return null;
	}

	/**
	 * Get Call source. This function can be called with events:
	 * <ul>
	 * <li>REGISTER_USER_SUCESSFUL
	 * <li>REGISTER_USER_NOT_FOUND
	 * <li>REGISTER_USER_FAIL
	 * <li>SERVER_INTERNAL_ERROR
	 * </ul>
	 * When source is not a EndPoint this method returns null
	 * 
	 * @return EndPoint generating the event
	 */
	public EndPoint getEndPointSource() {
		if (source instanceof EndPoint)
			return (EndPoint) source;
		else
			return null;
	}

	/**
	 * Returns the event type
	 * 
	 * @return Event type
	 */
	public EndpointEventEnum getEventType() {
		return eventType;
	}

	@Override
	public String toString() {
		return eventType.toString();
	}
}
