package com.kurento.commons.ua;

import com.kurento.commons.ua.exception.ServerInternalErrorException;

/**
 * This class represents the service EndPoint. It is associated to a URI, so
 * any call addressed to that URI will be multiplexed by the UA. The
 * same way, outgoing calls will be generated by the EndPoint URI
 * <p>
 * The EndPoint together with the {@link EndPointListener} provides a
 * control interface based in the telephone model of use, where the management
 * concepts are: dial, ringing, hang-up, etc...
 * 
 * @author Kurento
 * 
 */
public interface EndPoint {

	/**
	 * Terminates the EndPoint. This method causes the UA to un-register the
	 * URI and not to accept any incoming or outgoing call addressed to it
	 * 
	 * @throws ServerInternalErrorException
	 */
	public void terminate() throws ServerInternalErrorException;

	/**
	 * Creates a new outgoing call and initiates the negotiation with the
	 * called party specified. In order to start the procedure it must be
	 * provided a CallListener that will receive call events
	 * <p>
	 * Method returns control immediately after it is called. Negotiation and
	 * setup is carried out asynchronously and progress is notified through
	 * events to the controller
	 * 
	 * @param remoteParty
	 *            Called party
	 * @param callController
	 *            Listener of Call events
	 * @return the call object
	 * @throws ServerInternalErrorException
	 *             If an error occurts preventing the local UA to initiate the
	 *             procedure
	 */
	public Call dial(String remoteParty, CallListener callController)
			throws ServerInternalErrorException;

	/**
	 * Creates a new outgoing call and initiates the negotiation with the called
	 * party specified. In order to start the procedure it must be provided a
	 * CallListener that will receive call events
	 * <p>
	 * Method returns control immediately after it is called. Negotiation and
	 * setup is carried out asynchronously and progress is notified through
	 * events to the controller
	 * 
	 * @param remoteParty
	 *            Called party
	 * @param attributes
	 *            Extra attributes to be added to the call
	 * @param callController
	 *            Listener of Call events
	 * 
	 * @return the call object
	 * @throws ServerInternalErrorException
	 *             If an error occurts preventing the local UA to initiate the
	 *             procedure
	 */
	public Call dial(String remoteParty, CallAttributes attributes,
			CallListener callController)
			throws ServerInternalErrorException;

	/**
	 * Gets the local URI of this endpoint
	 * 
	 * @return The endpoint local URI
	 */
	public String getUri();

	/**
	 * Adds a new listener to be notified about the endpoint events
	 * 
	 * @param listener
	 *            The listener
	 */
	public void addListener(EndPointListener listener);

	/**
	 * Removes a listener that does not want to receive more events
	 * 
	 * @param listener
	 *            The listener
	 */
	public void removeListener(EndPointListener listener);

	/**
	 * Returns the conference manager that allows conference creation
	 * 
	 * @return The conference manager or null if this EndPoint does not support
	 *         conferences
	 */
	public ConferenceManager getConferenceManager();
}
