package com.kurento.commons.ua;

import java.text.ParseException;

import com.kurento.commons.ua.exception.ServerInternalErrorException;

/**
 * SIP User Agent is the software element thats manages SIP protocol internals.
 * Its functions are
 * <ul>
 * <li>Encode and decode SIP messages. It must be able to handle header values
 * <li>Send and receive SIP packets
 * <li>Register and un-register SIPURI contacts. It manages a list of active {@link EndPoint}
 * <li>Multiplex SIP messages among SipEndPoints. Automatically discard SIP messages not addressed
 * to any known EndPoint
 * 
 * @version 1.0.0
 */
public interface UA {

	// public UserAgentHeader getUserAgentHeader();
	
	/**
	 * Returns IP address where SIP stack listens
	 * @return Local IP address
	 */
	public String getLocalAddress();

	/**
	 * Returns port number where local SIP stack is binded
	 * @return Local port
	 */
	public int getLocalPort();

	/**
	 * Returns SIP Proxy IP address where SIP messages are sent
	 * @return SIP Proxy address
	 */
	public String getProxyAddress();

	/**
	 * Returns Proxy port number where SIP messages are sent
	 * @return SIP Proxy port
	 */
	public int getProxyPort();

	/**
	 * Terminate the UA. This process will perform the procedure below
	 * <ul>
	 * <li>Terminate all Call managed by this UA
	 * <li>Un-register SIPURI from all EndPoint
	 * <li>Terminate the SIP stack and free the network socket
	 * </ul>
	 */
	public void terminate();

	/**
	 * Creates a new EndPoint for the given SIPURI (user@realm) and registers
	 * a contact for that SIPURI in the configured REGISTRAR. On registration
	 * it is mandatory to provide a reference to the listener object that will
	 * receive all events generated by the EndPoint
	 * 
	 * @param user
	 *            User name of the SIPURI
	 * @param realm
	 *            Domain name of the SIPURI
	 * @param password
	 *            User password if authentication is enabled on the REGISTRAR
	 * @param expires
	 *            Contact expire time
	 * @param handler
	 *            Listener object receiving events from the created EndPoint
	 * @return Created EndPoint managing SIPURI
	 * @throws ParseException
	 *             if forbidden characters are provided for the user or realm
	 *             parameters
	 * @throws ServerInternalErrorException
	 *             if an internal error is found that prevents the registration
	 *             process to complete
	 */
	public EndPoint registerEndPoint(String user, String realm,
			String password, int expires, EndPointListener handler)
			throws ParseException, ServerInternalErrorException;

}