package com.kurento.commons.sip.event;

import java.util.EventObject;

import com.kurento.commons.sip.SipCall;

/**
 * SipCallEvent is generated by the SipCall when there is a relevant transition
 * to be notified
 * 
 * @author Kurento
 * 
 */
public class SipCallEvent extends EventObject {

	private static final long serialVersionUID = -6895550063104778497L;

	/**
	 * Call negotiation has completed successfully and media channels are setup
	 */
	public static final SipEventType CALL_SETUP = EventTypeEnum.CALL_SETUP;
	
	/**
	 * Call rejected by the called party
	 */
	public static final SipEventType CALL_REJECT = EventTypeEnum.CALL_REJECT;
	
	/**
	 * Call canceled by the calling party
	 */
	public static final SipEventType CALL_CANCEL = EventTypeEnum.CALL_CANCEL;
	
	/**
	 * Call terminated (hang up) by one of the parties
	 */
	public static final SipEventType CALL_TERMINATE = EventTypeEnum.CALL_TERMINATE;
	
	/**
	 * Call setup failure due to a protocol problem
	 */
	public static final SipEventType CALL_ERROR = EventTypeEnum.CALL_ERROR;

	/**
	 * Call setup failure due to incompatible media formats
	 */
	public static final SipEventType MEDIA_NOT_SUPPORTED = EventTypeEnum.MEDIA_NOT_SUPPORTED;
	
	/**
	 * Call setup failure due to lack of media resources. No ports available
	 */
	public static final SipEventType MEDIA_RESOURCE_NOT_AVAILABLE = EventTypeEnum.MEDIA_RESOURCE_NOT_AVAILABLE;

	/**
	 * Internal error within the local party prevents a normal negotiation flow
	 */
	public static final SipEventType SERVER_INTERNAL_ERROR = EventTypeEnum.SERVER_INTERNAL_ERROR;

	private SipEventType eventType;

	public SipCallEvent(SipEventType eventType, SipCall source) {
		super(source);
		this.eventType = eventType;
	}

	/**
	 * Set event source. The SipCall originating the event
	 * @param source
	 */
	public void setSource(SipCall source) {
		this.source = source;
	}

	/**
	 * Get SipCall that sourced the event
	 */
	public SipCall getSource() {
		return (SipCall) source;
	}

	/**
	 * Set the event that has to be notified
	 * @param eventType
	 */
	public void setEventType(SipEventType eventType) {
		this.eventType = eventType;
	}

	/**
	 * Returns the event type
	 * @return Event type
	 */
	public SipEventType getEventType() {
		return eventType;
	}

	public String toString() {
		return eventType.toString();
	}

}
